###########################################################################
# (No, I don't know how to go recursive. Screw you.)
# the .cpp should be in the same folders as this Makefile.
# this makefile compiles every .cpp file into .o, then link them.
# Makefile adapted from : http://gl.developpez.com/tutoriel/outil/makefile/
###########################################################################